version: '3'
services:
  neo-db:
    image: neo4j:latest
    ports:
      - 7474:7474
      - 7473:7473
      - 7687:7687
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_AUTH=none
      - NEO4J_PLUGINS=["apoc"]
    volumes:
      - data:/data
      - logs:/logs

  python-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./:/source
    environment:
      - NEO4J_URI=neo4j://neo-db:7687
      - API_PORT=8000
      - API_AUTORELOAD=true
    depends_on:
     - neo-db
volumes:
  data:
  logs:
